import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
""")

src += Glob('wdt/*.c')
CPPPATH += [cwd + '/wdt']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
