import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
app.c
""")

src += Glob('common/datapacket/*.c')
CPPPATH += [cwd + '/common/datapacket']

src += Glob('common/cputemp/*.c')
CPPPATH += [cwd + '/common/cputemp']

src += Glob('common/iwdg/*.c')
CPPPATH += [cwd + '/common/iwdg']

src += Glob('common/json/*.c')
CPPPATH += [cwd + '/common/json']

src += Glob('common/list/*.c')
CPPPATH += [cwd + '/common/list']

src += Glob('common/devcfg/*.c')
CPPPATH += [cwd + '/common/devcfg']

src += Glob('btn/*.c')
CPPPATH += [cwd + '/btn']

src += Glob('aliiot/*.c')
CPPPATH += [cwd + '/aliiot']

src += Glob('mqtt/*.c')
CPPPATH += [cwd + '/mqtt']

src += Glob('manager/*.c')
CPPPATH += [cwd + '/manager']

src += Glob('tm1637/*.c')
CPPPATH += [cwd + '/tm1637']

src += Glob('network/*.c')
CPPPATH += [cwd + '/network']

src += Glob('snmp/*.c')
CPPPATH += [cwd + '/snmp']

src += Glob('modbus/*.c')
CPPPATH += [cwd + '/modbus']

src += Glob('web/*.c')
CPPPATH += [cwd + '/web']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
