/*
 * dt_dingtalk.h
 *
 *  Created on: 2019Äê11ÔÂ20ÈÕ
 *      Author: luozhiyong
 */

#ifndef SPDU_BSP_STM32_STM32F429_ATK_APOLLO_APPLICATIONS_DINGTALK_DT_DINGTALK_H_
#define SPDU_BSP_STM32_STM32F429_ATK_APOLLO_APPLICATIONS_DINGTALK_DT_DINGTALK_H_
#include "dt_cfg.h"

void dt_talk(char *data);


#endif /* SPDU_BSP_STM32_STM32F429_ATK_APOLLO_APPLICATIONS_DINGTALK_DT_DINGTALK_H_ */
